description: |
  Detects Obfuscated Powershell via use Rundll32 in Scripts
name: Invoke-Obfuscation Via Use Rundll32 - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:securityy
type: any
priority: 3
