description: |
  Detects Obfuscated Powershell via RUNDLL LAUNCHER
name: Invoke-Obfuscation RUNDLL LAUNCHER - Security
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:security AND (event.code.keyword:4697 AND (winlog.event_data.ServiceFileName.keyword:*rundll32.exe*
        AND winlog.event_data.ServiceFileName.keyword:*shell32.dll* AND winlog.event_data.ServiceFileName.keyword:*shellexec_rundll*
        AND winlog.event_data.ServiceFileName.keyword:*powershell*))
type: any
priority: 2
mitre_attack_tactic:
- defense-evasion
- execution
mitre_attack_technique:
- t1027
- t1059.001
risk: medium
