description: |
  Detects certificate creation with template allowing risk permission subject
name: ADCS Certificate Template Configuration Vulnerability
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:security AND ((event.code.keyword:4898 AND winlog.event_data.TemplateContent.keyword:*ct_flag_enrollee_supplies_subject*) OR (event.code.keyword:4899 AND winlog.event_data.NewTemplateContent.keyword:*ct_flag_enrollee_supplies_subject*))
type: any
priority: 1
