description: |
  Detects Obfuscated use of stdin to execute PowerShell
name: Invoke-Obfuscation STDIN+ Launcher - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:securityy
type: any
priority: 3
