description: |
  Detects Obfuscated use of Clip.exe to execute PowerShell
name: Invoke-Obfuscation CLIP+ Launcher - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:Security AND (event.code.keyword:4697 AND (winlog.event_data.ServiceFileName.keyword:*cmd* AND winlog.event_data.ServiceFileName.keyword:*&&* AND winlog.event_data.ServiceFileName.keyword:*clipboard]::*))
type: any
priority: 3
