description: |
  Detects Obfuscated use of Environment Variables to execute PowerShell
name: Invoke-Obfuscation VAR+ Launcher - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:Security AND (event.code.keyword:4697 AND (winlog.event_data.ServiceFileName.keyword:*cmd* AND winlog.event_data.ServiceFileName.keyword:*\"set* AND winlog.event_data.ServiceFileName.keyword:*\-f*) AND (winlog.event_data.ServiceFileName.keyword:(*\/c* OR *\/r*)))
type: any
priority: 3
