description: |
  Detects Obfuscated Powershell via use Clip.exe in Scripts
name: Invoke-Obfuscation Via Use Clip - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
