description: |
  Detects Obfuscated Powershell via RUNDLL LAUNCHER
name: Invoke-Obfuscation RUNDLL LAUNCHER - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:securityy
type: any
priority: 2
