description: |
  Detects Obfuscated Powershell via use MSHTA in Scripts
name: Invoke-Obfuscation Via Use MSHTA - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:securityy
type: any
priority: 3
