description: |
  Detects Obfuscated Powershell via VAR++ LAUNCHER
name: Invoke-Obfuscation VAR++ LAUNCHER OBFUSCATION - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
