description: |
  Detects Obfuscated use of Environment Variables to execute PowerShell
name: Invoke-Obfuscation VAR+ Launcher - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
