description: |
  Detects certificate creation with template allowing risk permission subject
name: ADCS Certificate Template Configuration Vulnerability
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 1
