description: |
  Detects certificate creation with template allowing risk permission subject and risky EKU
name: ADCS Certificate Template Configuration Vulnerability with Risky EKU
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:security AND (((event.code.keyword:4898 AND (winlog.event_data.TemplateContent.keyword:(*1.3.6.1.5.5.7.3.2*
        OR *1.3.6.1.5.2.3.4* OR *1.3.6.1.4.1.311.20.2.2* OR *2.5.29.37.0*))) AND winlog.event_data.TemplateContent.keyword:*ct_flag_enrollee_supplies_subject*)
        OR ((event.code.keyword:4899 AND (winlog.event_data.NewTemplateContent.keyword:(*1.3.6.1.5.5.7.3.2*
        OR *1.3.6.1.5.2.3.4* OR *1.3.6.1.4.1.311.20.2.2* OR *2.5.29.37.0*))) AND 
        winlog.event_data.NewTemplateContent.keyword:*ct_flag_enrollee_supplies_subject*))
type: any
priority: 3
mitre_attack_tactic:
- privilege-escalation
- credential-access
mitre_attack_technique: []
risk: high
