description: |
  Detects Obfuscated use of Clip.exe to execute PowerShell
name: Invoke-Obfuscation CLIP+ Launcher - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:securityy
type: any
priority: 3
