description: |
  Detects Obfuscated Powershell via COMPRESS OBFUSCATION
name: Invoke-Obfuscation COMPRESS OBFUSCATION - Security
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:securityy
type: any
priority: 2
