description: |
  Detects certificate creation with template allowing risk permission subject and risky EKU
name: ADCS Certificate Template Configuration Vulnerability with Risky EKU
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
