description: |
  Detects Obfuscated Powershell via use MSHTA in Scripts
name: Invoke-Obfuscation Via Use MSHTA - Security
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:security AND (event.code.keyword:4697 AND (winlog.event_data.ServiceFileName.keyword:*mshta*
        AND winlog.event_data.ServiceFileName.keyword:*vbscript\:createobject* AND
        winlog.event_data.ServiceFileName.keyword:*.run* AND winlog.event_data.ServiceFileName.keyword:*window.close*))
type: any
priority: 3
mitre_attack_tactic:
- defense-evasion
- execution
mitre_attack_technique:
- t1027
- t1059.001
risk: high
