description: |
  This rule detects a suspicious crash of the Microsoft Malware Protection Engine
name: Microsoft Malware Protection Engine Crash - WER
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
