description: |
  Detects Rclone config files being created
name: Rclone Config File Creation
index: winlogbeat-*
filter:
- query:
    query_string:
      query: file.path.keyword:*\:\\users\\* AND file.path.keyword:*\\.config\\rclone\\*
type: any
priority: 2
mitre_attack_tactic:
- exfiltration
mitre_attack_technique:
- t1567.002
risk: medium
