description: |
  Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
name: UAC Bypass Using MSConfig Token Modification - File
index: winlogbeat-*
filter:
- query:
    query_string:
      query: file.path.keyword:c\:\\users\\* AND file.path.keyword:*\\appdata\\local\\temp\\pkgmgr.exe
type: any
priority: 3
mitre_attack_tactic:
- defense-evasion
- privilege-escalation
mitre_attack_technique:
- t1548.002
risk: high
