description: |
  A General detection for a new application in AppCompat. This indicates an application executing for the first time on an endpoint.
name: New Application in AppCompat
index: winlogbeat-*
filter:
- query:
    query_string:
      query: registry.path.keyword:*\\appcompatflags\\compatibility\ assistant\\store\\*
type: any
priority: 0
mitre_attack_tactic:
- execution
mitre_attack_technique:
- t1204.002
risk: informational
