description: |
  Detects changes to the AppInstaller (winget) admin settings. Such as enabling local manifest installations or disabling installer hash checks
name: Winget Admin Settings Modification
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 1
