description: |
  Detects registry modifications that disable Privacy Settings Experience
name: Disable Privacy Settings Experience in Registry
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
