description: |
  A General detection for a new application in AppCompat. This indicates an application executing for the first time on an endpoint.
name: New Application in AppCompat
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 0
