description: |
  Detects installation of new shim databases that try to patch sections of known processes for potential process injection or persistence.
name: Suspicious Shim Database Patching Activity
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
