description: |
  Detects changes to the AppInstaller (winget) admin settings. Such as enabling local manifest installations or disabling installer hash checks
name: Winget Admin Settings Modification
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: process.executable.keyword:*\\winget.exe AND registry.path.keyword:\\registry\\a\\* AND registry.path.keyword:*\\localstate\\admin_settings
type: any
priority: 1
