description: |
  Detects activity when Windows Defender Firewall has been reset to its default configuration
name: Windows Defender Firewall Has Been Reset To Its Default Configuration
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:Microsoft\-Windows\-Windows\ Firewall\ With\ Advanced\ Security\/Firewall AND (event.code.keyword:(2032 OR 2060))
type: any
priority: 1
