description: |
  Detects activity when Windows Defender Firewall has been reset to its default configuration
name: Windows Defender Firewall Has Been Reset To Its Default Configuration
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 1
