description: |
  Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
  
name: Security Support Provider (SSP) Added to LSA Configuration
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
