description: |
  Detects the addition of a SSP to the registry. Upon a reboot or API call, SSP DLLs gain access to encrypted and plaintext passwords stored in Windows.
  
name: Security Support Provider (SSP) Added to LSA Configuration
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: (registry.path.keyword:(*\\control\\lsa\\security\ packages OR *\\control\\lsa\\osconfig\\security\ packages)) AND (NOT (process.executable.keyword:(c\:\\windows\\system32\\msiexec.exe OR c\:\\windows\\syswow64\\msiexec.exe)))
type: any
priority: 3
