description: |
  This rule detects a DHCP server error in which a specified Callout DLL (in registry) could not be loaded
name: DHCP Server Error Failed Loading the CallOut DLL
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:systemm
type: any
priority: 3
