description: |
  This rule detects a DHCP server in which a specified Callout DLL (in registry) was loaded
name: DHCP Server Loaded the CallOut DLL
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
