description: |
  This rule detects a DHCP server error in which a specified Callout DLL (in registry) could not be loaded
name: DHCP Server Error Failed Loading the CallOut DLL
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:system AND ((event.code.keyword:(1031 OR 1032
        OR 1034)) AND winlog.provider_name.keyword:microsoft\-windows\-dhcp\-server)
type: any
priority: 3
mitre_attack_tactic:
- defense-evasion
mitre_attack_technique:
- t1574.002
risk: high
