description: |
  An application has been removed. Check if it is critical.
name: Application Uninstalled
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:applicationn
type: any
priority: 1
