description: |
  Detects when an attacker tries to hide from Sysmon by disabling or stopping it
name: Sysmon Configuration Modification
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
