description: |
  Detects when an adversary is trying to hide it's action from Sysmon logging based on error messages
name: Sysmon Configuration Error
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
