description: |
  Detects the pattern of UAC Bypass using a msconfig GUI hack (UACMe 55)
name: UAC Bypass Using MSConfig Token Modification - Process
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
