description: |
  Detects calls to the "terminate" function via wmic in order to kill an application
name: Application Terminated Via Wmic.EXE
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
