description: |
  Detects actions caused by the RedMimicry Winnti playbook a automated breach emulations utility
name: HackTool - RedMimicry Winnti Playbook Execution
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: (process.executable.keyword:(*\rundll32.exe OR *\cmd.exe)) AND (process.command_line.keyword:(*gthread-3.6.dll* OR *\windows\temp\tmp.bat* OR *sigcmm-2.4.dll*))
type: any
priority: 3
