description: |
  Detects the removal or uninstallation of an application via "Wmic.EXE".
name: Application Removed Via Wmic.EXE
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
