description: |
  Detects the execution of DeviceCredentialDeployment to hide a process from view
name: DeviceCredentialDeployment Execution
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
