description: |
  Detects when a user enable developer features such as "Developer Mode" or "Application Sideloading". Which allows the user to install untrusted packages.
name: Potential Signing Bypass Via Windows Developer Features
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
