description: |
  Detect malicious GPO modifications can be used to implement many other malicious behaviors.
name: Modify Group Policy Settings
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
