description: |
  Detects the execution of "ConfigSecurityPolicy.EXE", a binary part of Windows Defender used to manage settings in Windows Defender.
  Users can configure different pilot collections for each of the co-management workloads.
  It can be abused by attackers in order to upload or download files.
  
name: Arbitrary File Download Via ConfigSecurityPolicy.EXE
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
