description: |
  Detects the execution of DeviceCredentialDeployment to hide a process from view
name: DeviceCredentialDeployment Execution
index: winlogbeat-*
filter:
- query:
    query_string:
      query: process.executable.keyword:*\\devicecredentialdeployment.exe
type: any
priority: 2
mitre_attack_tactic:
- defense-evasion
mitre_attack_technique:
- t1218
risk: medium
