description: |
  Ntvdm.exe allows the execution of 16-bit Windows applications on 32-bit Windows operating systems, as well as the execution of both 16-bit and 32-bit DOS applications
name: Start of NT Virtual DOS Machine
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
