description: |
  Detects actions caused by the RedMimicry Winnti playbook a automated breach emulations utility
name: HackTool - RedMimicry Winnti Playbook Execution
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
