description: |
  Detect malicious GPO modifications can be used to implement many other malicious behaviors.
name: Modify Group Policy Settings
index: winlogbeat-*
filter:
- query:
    query_string:
      query: (winlog.event_data.image.keyword:*\\reg.exe OR winlog.event_data.originalfilename.keyword:reg.exe)
        AND process.command_line.keyword:*\\software\\policies\\microsoft\\windows\\system*
        AND (process.command_line.keyword:(*grouppolicyrefreshtimedc* OR *grouppolicyrefreshtimeoffsetdc*
        OR *grouppolicyrefreshtime* OR *grouppolicyrefreshtimeoffset* OR *enablesmartscreen*
        OR *shellsmartscreenlevel*))
type: any
priority: 2
mitre_attack_tactic:
- defense-evasion
- privilege-escalation
mitre_attack_technique:
- t1484.001
risk: medium
