description: |
  Detects calls to the "terminate" function via wmic in order to kill an application
name: Application Terminated Via Wmic.EXE
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: (winlog.event_data.image.keyword:*\wmic.exe OR winlog.event_data.originalfilename.keyword:wmic.exe) AND (process.command_line.keyword:*call* AND process.command_line.keyword:*terminate*)
type: any
priority: 2
