description: |
  Detects potential installation or installation attempts of known malicious appx packages
name: Potential Malicious AppX Package Installation Attempts
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-appxdeploymentserver\/operationall
type: any
priority: 2
