description: |
  Detects an appx package added to the pipeline of the "to be processed" packages which was downloaded from a suspicious domain.
  
name: Suspicious Remote AppX Package Locations
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
