description: |
  Detects an appx package added to the pipeline of the "to be processed" packages which was downloaded from a suspicious domain.
  
name: Suspicious Remote AppX Package Locations
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-appxdeploymentserver\/operational AND (event.code.keyword:854 AND (winlog.event_data.Path.keyword:(*.githubusercontent.com* OR *anonfiles.com* OR *cdn.discordapp.com* OR *ddns.net* OR *dl.dropboxusercontent.com* OR *ghostbin.co* OR *glitch.me* OR *gofile.io* OR *hastebin.com* OR *mediafire.com* OR *mega.nz* OR *onrender.com* OR *pages.dev* OR *paste.ee* OR *pastebin.com* OR *pastebin.pl* OR *pastetext.net* OR *privatlab.com* OR *privatlab.net* OR *send.exploit.in* OR *sendspace.com* OR *storage.googleapis.com* OR *storjshare.io* OR *supabase.co* OR *temp.sh* OR *transfer.sh* OR *trycloudflare.com* OR *ufile.io* OR *w3spaces.com* OR *workers.dev*)))
type: any
priority: 3
