description: |
  Detects an appx package added the pipeline of the "to be processed" packages which is located in suspicious locations
name: Suspicious AppX Package Locations
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-appxdeploymentserver\/operationall
type: any
priority: 3
