description: |
  Detects an appx package installation with the error code "0x80073cff" which indicates that the package didn't meet the signing requirements and could be suspicious
name: Suspicious AppX Package Installation Attempt
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
