description: |
  Detects an appx package added the pipeline of the "to be processed" packages which is located in uncommon locations
name: Uncommon AppX Package Locations
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 2
