description: |
  Detects application popup reporting a failure of the Sysmon service
name: Sysmon Application Crashed
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:system AND (winlog.provider_name.keyword:application\
        popup AND event.code.keyword:26 AND (winlog.event_data.Caption.keyword:(sysmon64.exe\
        \-\ application\ error OR sysmon.exe\ \-\ application\ error)))
type: any
priority: 3
mitre_attack_tactic:
- defense-evasion
mitre_attack_technique:
- t1562
risk: high
