description: |
  Detects application popup reporting a failure of the Sysmon service
name: Sysmon Application Crashed
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:systemm
type: any
priority: 3
