description: |
  Detects when an attacker calls the "ALTER SERVER AUDIT" or "DROP SERVER AUDIT" transaction in order to delete or disable audit logs on the server
name: MSSQL Disable Audit Settings
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:applicationn
type: any
priority: 3
