description: |
  Detects the Setting of Windows Defender Exclusions
name: Windows Defender Exclusions Added
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-windows\ defender\/operational
        AND (event.code.keyword:5007 AND winlog.event_data.NewValue.keyword:*\\microsoft\\windows\
        defender\\exclusions*)
type: any
priority: 2
mitre_attack_tactic:
- defense-evasion
mitre_attack_technique:
- t1562.001
risk: medium
