description: |
  Detects when someone is adding or removing applications or folders from exploit guard "ProtectedFolders" or "AllowedApplications"
  
name: Windows Defender Exploit Guard Tamper
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:Microsoft-Windows-Windows Defender/Operational AND (((event.code.keyword:5007 AND winlog.event_data.NewValue.keyword:*\windows defender\windows defender exploit guard\controlled folder access\allowedapplications*) AND (winlog.event_data.NewValue.keyword:(*\users\public* OR *\appdata\local\temp* OR *\desktop* OR *\perflogs* OR *\windows\temp*))) OR (event.code.keyword:5007 AND winlog.event_data.OldValue.keyword:*\windows defender\windows defender exploit guard\controlled folder access\protectedfolders*))
type: any
priority: 3
