description: |
  Detects disabling of the "Automatic Sample Submission" feature of Windows Defender.
name: Windows Defender Submit Sample Feature Disabled
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-windows\ defender\/operationall
type: any
priority: 1
