description: |
  Detects the Setting of Windows Defender Exclusions
name: Windows Defender Exclusions Added
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-windows\ defender\/operationall
type: any
priority: 2
