description: |
  Detects when someone is adding or removing applications or folders from exploit guard "ProtectedFolders" or "AllowedApplications"
  
name: Windows Defender Exploit Guard Tamper
index: "winlogbeat-*"
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-windows\ defender\/operationall
type: any
priority: 3
