description: |
  Detects disabling of the "Automatic Sample Submission" feature of Windows Defender.
name: Windows Defender Submit Sample Feature Disabled
index: winlogbeat-*
filter:
- query:
    query_string:
      query: winlog.channel.keyword:microsoft\-windows\-windows\ defender\/operational
        AND (event.code.keyword:5007 AND winlog.event_data.NewValue.keyword:*\\real\-time\
        protection\\submitsamplesconsent\ \=\ 0x0*)
type: any
priority: 1
mitre_attack_tactic:
- defense-evasion
mitre_attack_technique:
- t1562.001
risk: low
