description: |
  Detects when someone is adding or removing applications or folders from exploit guard "ProtectedFolders" or "AllowedApplications"
  
name: Windows Defender Exploit Guard Tamper
index: "winlogbeat-*"
filter:
- query:
    query_string:
type: any
priority: 3
